GET http://localhost:8080/api/v1/user/list

###

GET http://localhost:8080/api/v1/user/3/id

###

POST http://localhost:8080/api/v1/user/
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

###

PUT http://localhost:8080/api/v1/user/
Content-Type: application/json

{
  "id": 2,
  "login": "user2",
  "password": "user2"
}
###

DELETE http://localhost:8080/api/v1/user/3/id